### ISSUE TITLE
0.3.0 InvalidClient

### ISSUE THREAD

**Issue by ShayBox** [Spanfile/Ferrispot#2]
I updated to 0.3.0 and `user_client.refresh_access_token()` gives me an `Unhandled authentication error: InvalidClient` error (with and without pkce).  
I tested 0.2.1 and it worked, 0.3.0 doesn't, normal construction and code/state are valid.

EDIT: I'm also not able to use `?` on the result of `refresh_access_token` (and many more methods), errors never propagate and the program just freezes on error, but unwrap works.

I also wanted to ask if there's any control over playback implemented,  
Such as play/pause/stop/next/prev/shuffle/mute/repeat/volume.

**Comment by Spanfile** [comment]
I've published 0.3.1 that contains a fix for the invalid client error.

Can you show an example of the errors freezing the program?

Play, pause, resume, volume, shuffle and repeat are implemented in scoped clients. I'll implement next, previous and seek as well.

Edit: Next, previous and seek have been implemented in 0.3.2.

**Comment by ShayBox** [comment]
0.3.1 fixed the InvalidClient error for me :+1:

I wasn't able to reproduce the error freezing in an example project, I think it's because I spawn a separate thread for each plugin in my project and using `?` doesn't propagate outside the thread with `abi_stable`, only panics, sorry about that.

I'll be using all those methods very soon, thank you.

The last problem I'm having is that `currently_playing_item` doesn't return items from private playlists (such as liked)  
https://developer.spotify.com/console/get-users-currently-playing-track  
The demo returns them but Ferrispot doesn't, here's the result I get from that page  
https://pastebin.com/1wSg2Q9B

**Comment by Spanfile** [comment]
The Liked Songs playlist turns out to be a special case that Ferrispot's model doesn't account for yet, but I'm working on updating it.

**Comment by Spanfile** [comment]
I've published 0.3.3 that should be able to deal with the special Liked Songs playlist.

**Comment by ShayBox** [comment]
Thank you, that fixed it for me :+1:

**Comment by Spanfile** [comment]
Ah yep, that's because the entire playing context is `null`. It's going to be a breaking change changing the context in the model to be an `Option<Context>` instead. I'll group the change with a bunch of other breaking changes as well and release them as 0.4.0 later.

**Comment by Spanfile** [comment]
I've released 0.4.0 that includes a fix for the missing context, but also overhauls the endpoint requests. Please see the changelog for more details.
