### ISSUE TITLE
Add Lyrics API Support?

### ISSUE THREAD

**Issue by ShayBox** [Spanfile/Ferrispot#5]
I found [akashrchandran](https://github.com/akashrchandran)/[spotify-lyrics-api](https://github.com/akashrchandran/spotify-lyrics-api) which seems to use an "unofficial" Spotify API to get lyrics.

I also found [Maxuss](https://github.com/Maxuss)/[verses](https://github.com/Maxuss/verses) which uses [lyricstify](https://github.com/lyricstify)/[lyricstify](https://github.com/lyricstify/lyricstify)'s API, I haven't looked into their API code but I assume they do the same thing.

Is this something Ferrispot can support? I don't know what exactly the API responds with, but it seems spotify-lyrics-api is able to get LRC ([which has a crate](https://crates.io/crates/lrc)) with [little PHP](https://github.com/akashrchandran/spotify-lyrics-api/blob/main/src/Spotify.php)

**Comment by Spanfile** [comment]
Ferrispot will strictly interact with the Spotify Web API only. These lyrics tools call an undocumented Spotify endpoint outside the Web API and spoof themselves as web browsers, which means using the endpoint programmatically is prohibited by the Spotify terms of service. Unless Spotify adds an endpoint to the Web API to retrieve lyrics, I won't be adding support for it.

**Comment by ShayBox** [comment]
Understandable, Spotify denied my production application request three times already, so I'll handle the code in my project.
